Repository salto-io/salto, pull requests merged in 2020-11, with the labels that each got.

#1587 Bump to version 0.1.36
  lerna.json
  packages/adapter-api/package.json
  packages/adapter-utils/package.json
  packages/cli/package.json
  packages/core/package.json
  packages/dag/package.json
  packages/dummy-adapter/package.json
  packages/e2e-credentials-store/package.json
  packages/file/package.json
  packages/hubspot-adapter/package.json
  packages/lang-server/package.json
  packages/logging/package.json
  packages/lowerdash/package.json
  packages/monitoring/package.json
  packages/netsuite-adapter/package.json
  packages/persistent-pool/package.json
  packages/salesforce-adapter/package.json
  packages/vscode/package.json
  packages/workspace/package.json
Labels: VERSION

#1610 Bump to version 0.1.37
  lerna.json
  packages/adapter-api/package.json
  packages/adapter-utils/package.json
  packages/cli/package.json
  packages/core/package.json
  packages/dag/package.json
  packages/dummy-adapter/package.json
  packages/e2e-credentials-store/package.json
  packages/file/package.json
  packages/hubspot-adapter/package.json
  packages/lang-server/package.json
  packages/logging/package.json
  packages/lowerdash/package.json
  packages/monitoring/package.json
  packages/netsuite-adapter/package.json
  packages/persistent-pool/package.json
  packages/salesforce-adapter/package.json
  packages/vscode/package.json
  packages/workspace/package.json
Labels: VERSION

#1618 Bump to version 0.1.38
  lerna.json
  packages/adapter-api/package.json
  packages/adapter-utils/package.json
  packages/cli/package.json
  packages/core/package.json
  packages/dag/package.json
  packages/dummy-adapter/package.json
  packages/e2e-credentials-store/package.json
  packages/file/package.json
  packages/hubspot-adapter/package.json
  packages/lang-server/package.json
  packages/logging/package.json
  packages/lowerdash/package.json
  packages/monitoring/package.json
  packages/netsuite-adapter/package.json
  packages/persistent-pool/package.json
  packages/salesforce-adapter/package.json
  packages/vscode/package.json
  packages/workspace/package.json
Labels: VERSION

#1621 SALTO-1048 Limit concurrent salesforce API calls
  packages/cli/e2e_test/NACL/salto.config/salesforce.nacl
  packages/core/test/workspace/local/workspace_config.test.ts
  packages/salesforce-adapter/config_doc.md
  packages/salesforce-adapter/e2e_test/custom_object_instances.test.ts
  packages/salesforce-adapter/package.json
  packages/salesforce-adapter/src/adapter.ts
  packages/salesforce-adapter/src/adapter_creator.ts
  packages/salesforce-adapter/src/client/client.ts
  packages/salesforce-adapter/src/config_change.ts
  packages/salesforce-adapter/src/constants.ts
  packages/salesforce-adapter/src/fetch.ts
  packages/salesforce-adapter/src/types.ts
  packages/salesforce-adapter/test/adapter.creator.test.ts
  packages/salesforce-adapter/test/adapter.discover.test.ts
  packages/salesforce-adapter/test/client.test.ts
  packages/salesforce-adapter/test/client.ts
Labels: non-backward-compatible

#1638 Bump to version 0.1.39
  lerna.json
  packages/adapter-api/package.json
  packages/adapter-utils/package.json
  packages/cli/package.json
  packages/core/package.json
  packages/dag/package.json
  packages/dummy-adapter/package.json
  packages/e2e-credentials-store/package.json
  packages/file/package.json
  packages/hubspot-adapter/package.json
  packages/lang-server/package.json
  packages/logging/package.json
  packages/lowerdash/package.json
  packages/marketo-adapter/package.json
  packages/monitoring/package.json
  packages/netsuite-adapter/package.json
  packages/persistent-pool/package.json
  packages/salesforce-adapter/package.json
  packages/vscode/package.json
  packages/workspace/package.json
Labels: VERSION

#1640 Netsuite: Use new SDF version, refactor client config, expose a new config option to limit import chunks in SDF
  packages/netsuite-adapter/config_doc.md
  packages/netsuite-adapter/e2e_test/adapter.test.ts
  packages/netsuite-adapter/e2e_test/adapter.ts
  packages/netsuite-adapter/package.json
  packages/netsuite-adapter/src/adapter.ts
  packages/netsuite-adapter/src/adapter_creator.ts
  packages/netsuite-adapter/src/client/client.ts
  packages/netsuite-adapter/src/config.ts
  packages/netsuite-adapter/src/constants.ts
  packages/netsuite-adapter/test/adapter.test.ts
  packages/netsuite-adapter/test/adapter_creator.test.ts
  packages/netsuite-adapter/test/client/client.test.ts
  packages/netsuite-adapter/test/client/client.ts
  packages/netsuite-adapter/test/config.test.ts
  yarn.lock
Labels: documentation, non-backward-compatible

#1652 Bump to version 0.1.40
  lerna.json
  packages/adapter-api/package.json
  packages/adapter-utils/package.json
  packages/cli/package.json
  packages/core/package.json
  packages/dag/package.json
  packages/dummy-adapter/package.json
  packages/e2e-credentials-store/package.json
  packages/file/package.json
  packages/hubspot-adapter/package.json
  packages/lang-server/package.json
  packages/logging/package.json
  packages/lowerdash/package.json
  packages/marketo-adapter/package.json
  packages/monitoring/package.json
  packages/netsuite-adapter/package.json
  packages/persistent-pool/package.json
  packages/salesforce-adapter/package.json
  packages/vscode/package.json
  packages/workspace/package.json
Labels: VERSION
